language: node_js
node_js:
    - 12
    - 10
    - 8

cache:
  npm: false

script:
  - npm run lint
  - npm run coverage

notifications:
    email:
        on_success: never
        on_failure: change

